#!/bin/bash

backend="bluetoothctl"
connected_device=""
scan_result=[]

#check whether bluetoothctl is installed and is working correctly
is_bluetoothctl_installed_correctly() {
	if [[ $($backend -v) == bluetoothctl* &&
	$($backend power on) == "Changing power on succeeded" &&
	$($backend list) == Controller* ]]; then
		echo $backend 'is installed and configured correctly'
	fi
}

get_already_paired_devices() {
	IFS=
	echo $($backend paired-devices);
}

print_connected_devices() {
	while read -r _ mac name; do
		if [[ $($backend info $mac | grep "Connected: yes") ]]; then
			printf "$name\n"
		fi
	done < <(get_already_paired_devices)
}

print_paired_devices() {
	while read -r _ mac name; do
			printf "$name\n"
	done < <(get_already_paired_devices)
}

connect_device() {
	$backend connect $2 && (
	echo $2 '(connected)';
	$connected_device="hello"
	);
	echo $connected_device;
}


disconnect_all_devices() {
	$($backend disconnect);
}

scan_for_devices() {
	echo 'Scan for devices';
}

get_main_menu() {
	echo -e "connected\npaired\nscan"
}

open_main_menu() {
	local submenu
	submenu=$(get_main_menu | dmenu -p "btmenu";)
	[[ $submenu ]] || exit 1

	if [[ $submenu == "connected" ]]; then
		print_connected_devices | dmenu -p "connected"
	elif [[ $submenu == "paired" ]]; then
		print_paired_devices | dmenu -p "paired"
	fi
}

open_main_menu

#connect_device $(get_already_paired_devices | dmenu);