#!/bin/bash

backend="bluetoothctl"

#check whether bluetoothctl is installed and is working correctly
is_bluetoothctl_installed_correctly() {
	if [[ $($backend -v) == bluetoothctl* &&
	$($backend power on) == "Changing power on succeeded" &&
	$($backend list) == Controller* ]]; then
		echo $backend 'is installed and configured correctly'
	fi
}

get_already_paired_devices() {
	IFS=
	echo $($backend paired-devices);
}

connect_device() {
	$backend connect $2;
}

connect_device $(get_already_paired_devices | dmenu);

